/**
 * This code was generated by Builder.io.
 */
"use client";
import * as React from "react";
import { useState } from "react";

type Color = {
  gray2: string;
  black: string;
  primary: string;
  gray4: string;
};

type Typography = {
  smallFontSize: string;
  smallFontWeight: string;
  smallLineHeight: string;
  pFontSize: string;
  pFontWeight: string;
};

export default function ContactModalComponent() {
  const [modalHidden, setModalHidden] = useState<boolean | null>(null);
  const [colors, setColors] = useState<Color | null>(null);
  const [typo, setTypo] = useState<Typography | null>(null);

  return (
    <>
      {modalHidden ? (
        <ContactModal
          colors={colors}
          typo={typo}
          onClose={() => setModalHidden(false)}
        />
      ) : null}
    </>
  );
}

type ContactModalProps = {
  colors: Color | null;
  typo: Typography | null;
  onClose: () => void;
};

function ContactModal({ colors, typo, onClose }: ContactModalProps) {
  return (
    <div className="box-border flex fixed top-0 left-0 flex-col shrink-0 justify-center items-center bg-gray-800 bg-opacity-50 size-full z-[100] max-md:flex max-sm:flex">
      <div
        className="flex relative flex-col p-6 w-full bg-white shadow-sm max-w-[600px] max-md:flex max-sm:flex max-sm:w-full"
        style={{ backgroundColor: colors?.gray2 }}
      >
        <button
          className="box-border object-contain overflow-hidden absolute top-3 right-3 shrink-0 mx-auto w-full aspect-square max-w-[24px] min-h-[20px] min-w-[20px] cursor-pointer"
          onClick={onClose}
          aria-label="Close modal"
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets%2F6e3ca42686fd4e17a8c29dc7e0b5666b%2Fe88c30258f984ae69bfb5b27c27d9c91"
            alt=""
            className="w-full h-full"
          />
        </button>
        <h2
          className="mb-6 text-3xl font-semibold leading-10 max-sm:font-semibold"
          style={{ color: colors?.black }}
        >
          Kontaktformular
        </h2>
        <form className="flex flex-col">
          <label htmlFor="name" className="sr-only">
            Name
          </label>
          <input
            type="text"
            id="name"
            placeholder="Name*"
            className="px-6 py-4 mb-6 text-lg font-medium tracking-widest leading-6 rounded-lg border border-solid border-zinc-200 max-sm:pt-1"
            style={{ color: colors?.black }}
            required
            aria-required="true"
          />
          <label htmlFor="email" className="sr-only">
            E-Mail
          </label>
          <input
            type="email"
            id="email"
            placeholder="E-Mail*"
            className="px-6 py-4 mb-6 text-lg font-medium tracking-widest leading-6 rounded-lg border border-solid border-zinc-200 max-sm:pt-1"
            style={{ color: colors?.black }}
            required
            aria-required="true"
          />
          <label htmlFor="message" className="sr-only">
            Nachricht
          </label>
          <textarea
            id="message"
            placeholder="Nachricht"
            required
            aria-required="true"
            className="px-6 py-4 mb-6 text-lg font-medium tracking-widest leading-6 rounded-lg border border-solid border-zinc-200"
            style={{ color: colors?.black }}
          />
          <div
            className="box-border relative shrink-0 mb-5 h-auto text-center max-sm:text-left"
            style={{
              fontSize: typo?.smallFontSize,
              fontWeight: typo?.smallFontWeight,
              color: colors?.gray4,
              lineHeight: typo?.smallLineHeight,
            }}
          >
            <p>
              Ich bin damit einverstanden, dass diese Daten zum Zweck der
              Kontaktaufnahme gespeichert und verarbeitet werden. Mir ist
              bekannt, dass ich meine Einwilligung jederzeit widerrufen kann.*
              <br />
              <br />* Kennzeichnet erforderliche Felder
            </p>
          </div>
          <button
            type="submit"
            className="box-border relative shrink-0 px-5 py-3.5 ml-auto text-center rounded-xl border border-none appearance-none cursor-pointer bg-[black] border-[black]"
            style={{
              backgroundColor: colors?.primary,
              fontSize: typo?.pFontSize,
              fontWeight: typo?.pFontWeight,
              color: colors?.black,
            }}
          >
            Senden
          </button>
        </form>
      </div>
    </div>
  );
}