/**
 * This code was generated by Builder.io.
 */
"use client";
import * as React from "react";
import { useState } from "react";
import Image from "next/image";

type Color = {
  gray4: string;
  black: string;
  gray3: string;
  primary: string;
};

type Typography = {
  smallFontSize: string;
  smallFontWeight: string;
};

type AccordionItemProps = {
  title: string;
  href?: string;
  onToggle: () => void;
  isOpen: boolean;
};

/**
 * AccordionItem component
 * @param {AccordionItemProps} props - The props for the AccordionItem component
 * @returns {JSX.Element} - The rendered AccordionItem component
 */
const AccordionItem: React.FC<AccordionItemProps> = ({
  title,
  href,
  onToggle,
  isOpen,
}) => {
  return (
    <div className="accordion">
      <button
        className="accordion-title flex relative flex-col p-2.5 bg-gray-200 max-md:bg-white w-full text-left"
        onClick={onToggle}
      >
        {href ? (
          <a href={href} className="flex flex-col text-left">
            <div
              dangerouslySetInnerHTML={{ __html: `<p>${title}</p>` }}
              className="builder-text"
            />
          </a>
        ) : (
          <div className="flex flex-col text-left">
            <div
              dangerouslySetInnerHTML={{ __html: `<p>${title}</p>` }}
              className="builder-text"
            />
          </div>
        )}
      </button>
      {isOpen && <div className="accordion-detail">Accordion Detail</div>}
    </div>
  );
};

/**
 * Navigation component
 * @returns {JSX.Element} - The rendered Navigation component
 */
function Navigation() {
  const [colors, setColors] = useState<Color | null>(null);
  const [typo, setTypo] = useState<Typography | null>(null);
  const [show, setShow] = useState<boolean>(false);
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const accordionItems = [
    {
      title: "Dienstleistungen",
      href: "{{ext_10}}",
    },
    {
      title: "E-Commerce",
    },
    {
      title: "Erweiterungen",
    },
    {
      title: "Über mich",
    },
  ];

  /**
   * Handles the accordion toggle
   * @param {number} index - The index of the accordion item
   */
  const handleAccordionToggle = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <div
      className="box-border flex sticky top-3 flex-col shrink-0 px-6 py-2 mb-3 h-auto rounded-xl bg-gray-50 bg-opacity-80 grow-0 z-[100] max-md:mx-3 max-sm:pl-3 max-sm:mx-3"
      style={{ maxWidth: "none" }}
    >
      <header className="box-border flex sticky top-3 flex-col grow shrink-0 self-stretch px-6 py-2 mx-auto mb-3 w-full h-auto rounded-xl bg-gray-50 bg-opacity-80 max-w-[1200px] z-[100] max-md:mx-3 max-sm:pl-3 max-sm:mx-3">
        <div className="flex flex-row w-full max-md:items-center max-sm:items-center">
          <div className="flex relative flex-row gap-5 justify-between items-center self-stretch my-1.5 w-full">
            <div className="flex relative flex-row gap-12 items-center self-stretch grow-[1.1674179080885916] max-md:items-center max-md:my-auto max-md:mr-auto max-md:w-full max-sm:justify-start">
              <div className="box-border flex relative flex-row shrink-0 items-center">
                <Image
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets%2F6e3ca42686fd4e17a8c29dc7e0b5666b%2F25ff05029a7446f78a40a61f6de4e723"
                  alt="FULLTime logo"
                  className="box-border object-contain overflow-hidden shrink-0 self-stretch aspect-[0.7] grow-0 h-[72px] w-[72px] max-md:grow max-md:mr-auto max-sm:mr-auto max-sm:max-h-[42px] max-sm:max-w-[53px] max-sm:min-w-[42px]"
                  width={72}
                  height={72}
                />
                <div className="box-border flex relative flex-col shrink-0 mr-auto ml-5">
                  <h1
                    className="box-border relative shrink-0 mr-auto h-auto text-3xl font-bold leading-7"
                    style={{ color: colors?.gray4 }}
                  >
                    FULLTime
                    <br />
                  </h1>
                  <p
                    className="box-border relative shrink-0 h-auto text-base leading-4"
                    style={{ color: colors?.gray4 }}
                  >
                    eCommerce
                    <br />
                  </p>
                </div>
              </div>
              <nav className="flex relative flex-col grow-[3.1608208817763215] max-md:hidden max-md:flex-row max-md:mr-auto max-sm:hidden">
                <ul className="flex relative flex-row gap-4 justify-start self-stretch max-md:justify-center">
                  <li
                    className="box-border relative shrink-0"
                    style={{
                      color: colors?.black,
                      fontSize: typo?.smallFontSize,
                      fontWeight: typo?.smallFontWeight,
                    }}
                  >
                    Dienstleistungen
                  </li>
                  <li
                    className="box-border relative shrink-0 ml-0.5 max-md:mx-0.5"
                    style={{
                      color: colors?.black,
                      fontSize: typo?.smallFontSize,
                      fontWeight: typo?.smallFontWeight,
                    }}
                  >
                    E-Commerce
                  </li>
                  <li
                    className="box-border relative shrink-0 ml-3 max-md:mx-2.5"
                    style={{
                      color: colors?.black,
                      fontSize: typo?.smallFontSize,
                      fontWeight: typo?.smallFontWeight,
                    }}
                  >
                    Erweiterungen
                  </li>
                  <li
                    className="box-border relative shrink-0"
                    style={{
                      color: colors?.black,
                      fontSize: typo?.smallFontSize,
                      fontWeight: typo?.smallFontWeight,
                    }}
                  >
                    Über mich
                  </li>
                </ul>
              </nav>
            </div>
            <div className="flex relative flex-row mt-px ml-auto w-auto grow-0 max-md:hidden max-sm:hidden">
              <a
                href="{{ext_12}}"
                className="box-border relative shrink-0 px-3 py-3.5 my-auto mr-4 ml-auto text-center rounded appearance-none cursor-pointer grow-0"
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  color: colors?.black,
                  fontSize: typo?.smallFontSize,
                  fontWeight: typo?.smallFontWeight,
                }}
              >
                Dokumentationen
              </a>
              <div
                className="box-border flex relative flex-col shrink-0 my-auto w-0.5 h-8 bg-stone-300"
                style={{ backgroundColor: colors?.gray3 }}
              />
              <div className="flex relative flex-row gap-4 ml-4">
                <button
                  className="box-border relative shrink-0 px-5 py-3.5 text-center rounded-xl appearance-none cursor-pointer grow-0"
                  style={{
                    backgroundColor: colors?.primary,
                    color: colors?.black,
                    fontSize: typo?.smallFontSize,
                    fontWeight: typo?.smallFontWeight,
                  }}
                  onClick={() => setShow(!show)}
                >
                  Kontakt
                </button>
              </div>
            </div>
          </div>
        </div>
        <Image
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets%2F6e3ca42686fd4e17a8c29dc7e0b5666b%2F25ff05029a7446f78a40a61f6de4e723"
          alt=""
          className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[3.87] min-h-[20px] min-w-[20px] max-md:flex max-md:w-6 max-md:h-6 max-md:max-w-[48px] max-sm:flex max-sm:ml-auto max-sm:w-6 max-sm:h-6"
          width={48}
          height={12}
        />
      </header>
      {show && (
        <section className="box-border flex relative flex-col shrink-0 max-md:flex max-md:py-5 max-sm:flex max-sm:py-5 max-sm:h-auto max-sm:grow-0">
          {accordionItems.map((item, index) => (
            <AccordionItem
              key={index}
              title={item.title}
              href={item.href}
              onToggle={() => handleAccordionToggle(index)}
              isOpen={activeIndex === index}
            />
          ))}
        </section>
      )}
    </div>
  );
}

export { Navigation };